"""
Router: /api/almoxarifado — Estoque de Insumos e Medicamentos — FMS Apuí/AM
Dados de referência municipal. situacao_dado = referencia_municipal.
"""
from __future__ import annotations
from fastapi import APIRouter, Depends, Query
from routers.auth import get_current_user, UserOut

router = APIRouter(prefix="/api/almoxarifado", tags=["almoxarifado"])


@router.get("/resumo")
async def resumo():
    return {
        "situacao_dado": "referencia_municipal",
        "municipio": "Apuí/AM",
        "referencia": "Jul/2026",
        "total_itens": 148,
        "itens_ok": 108,
        "itens_alerta": 26,
        "itens_critico": 9,
        "sem_estoque": 5,
        "vencendo_30d": 7,
        "valor_total_estoque": 184320.50,
        "fonte": "Referência municipal FMS Apuí/AM",
    }


@router.get("/lista")
async def lista(categoria: str = Query(None)):
    itens = [
        {
            "id": "CATMAT-000148",
            "nome": "Arteméter + Lumefantrina 20/120mg (cp)",
            "codigo": "CATMAT-000148",
            "categoria": "Antimalárico",
            "unidade": "cp",
            "estoque_atual": 2400,
            "estoque_minimo": 600,
            "estoque_maximo": 4800,
            "consumo_medio_mensal": 480,
            "meses_cobertura": 5.0,
            "lote": "AM2025-0891",
            "validade": "2027-03-31",
            "dias_vencimento": 607,
            "local": "Almoxarifado A — Prateleira 3",
            "status": "ok",
            "valor_unitario": 2.40,
            "ultimo_recebimento": "2026-05-12",
        },
        {
            "id": "CATMAT-000231",
            "nome": "Primaquina 15mg (cp)",
            "codigo": "CATMAT-000231",
            "categoria": "Antimalárico",
            "unidade": "cp",
            "estoque_atual": 1800,
            "estoque_minimo": 400,
            "estoque_maximo": 3600,
            "consumo_medio_mensal": 360,
            "meses_cobertura": 5.0,
            "lote": "PQ2025-0044",
            "validade": "2026-12-31",
            "dias_vencimento": 150,
            "local": "Almoxarifado A — Prateleira 3",
            "status": "ok",
            "valor_unitario": 0.85,
            "ultimo_recebimento": "2026-04-18",
        },
        {
            "id": "CATMAT-000087",
            "nome": "Artesunato injetável 60mg (amp)",
            "codigo": "CATMAT-000087",
            "categoria": "Antimalárico",
            "unidade": "amp",
            "estoque_atual": 24,
            "estoque_minimo": 20,
            "estoque_maximo": 120,
            "consumo_medio_mensal": 12,
            "meses_cobertura": 2.0,
            "lote": "AS2025-0016",
            "validade": "2027-06-30",
            "dias_vencimento": 697,
            "local": "Câmara fria — Medicamentos essenciais",
            "status": "alerta",
            "valor_unitario": 28.50,
            "ultimo_recebimento": "2026-03-05",
        },
        {
            "id": "CATMAT-000312",
            "nome": "Soro antiofídico (bothrópico) 10mL (amp)",
            "codigo": "CATMAT-000312",
            "categoria": "Soros e imunobiológicos",
            "unidade": "amp",
            "estoque_atual": 18,
            "estoque_minimo": 24,
            "estoque_maximo": 80,
            "consumo_medio_mensal": 8,
            "meses_cobertura": 2.25,
            "lote": "SRO2026-0003",
            "validade": "2027-08-31",
            "dias_vencimento": 758,
            "local": "Câmara fria — Prateleira 1",
            "status": "critico",
            "valor_unitario": 184.00,
            "ultimo_recebimento": "2026-02-20",
        },
        {
            "id": "CATMAT-000044",
            "nome": "Amoxicilina 500mg (cp)",
            "codigo": "CATMAT-000044",
            "categoria": "Antibiótico",
            "unidade": "cp",
            "estoque_atual": 5200,
            "estoque_minimo": 1000,
            "estoque_maximo": 8000,
            "consumo_medio_mensal": 1200,
            "meses_cobertura": 4.3,
            "lote": "AMX2026-0081",
            "validade": "2027-09-30",
            "dias_vencimento": 788,
            "local": "Almoxarifado B — Prateleira 1",
            "status": "ok",
            "valor_unitario": 0.22,
            "ultimo_recebimento": "2026-06-02",
        },
        {
            "id": "CATMAT-000072",
            "nome": "Metformina 850mg (cp)",
            "codigo": "CATMAT-000072",
            "categoria": "Antidiabético",
            "unidade": "cp",
            "estoque_atual": 3800,
            "estoque_minimo": 800,
            "estoque_maximo": 6000,
            "consumo_medio_mensal": 950,
            "meses_cobertura": 4.0,
            "lote": "MET2026-0022",
            "validade": "2027-11-30",
            "dias_vencimento": 850,
            "local": "Almoxarifado B — Prateleira 4",
            "status": "ok",
            "valor_unitario": 0.18,
            "ultimo_recebimento": "2026-05-28",
        },
        {
            "id": "CATMAT-000098",
            "nome": "Insulina NPH 100UI/mL (frasco)",
            "codigo": "CATMAT-000098",
            "categoria": "Antidiabético",
            "unidade": "frasco",
            "estoque_atual": 48,
            "estoque_minimo": 40,
            "estoque_maximo": 200,
            "consumo_medio_mensal": 38,
            "meses_cobertura": 1.3,
            "lote": "INS2026-0009",
            "validade": "2026-09-30",
            "dias_vencimento": 48,
            "local": "Câmara fria — Insulinas",
            "status": "alerta",
            "valor_unitario": 9.80,
            "ultimo_recebimento": "2026-05-10",
        },
        {
            "id": "CATMAT-000201",
            "nome": "Sulfato ferroso 40mg (cp)",
            "codigo": "CATMAT-000201",
            "categoria": "Suplemento",
            "unidade": "cp",
            "estoque_atual": 0,
            "estoque_minimo": 500,
            "estoque_maximo": 3000,
            "consumo_medio_mensal": 480,
            "meses_cobertura": 0.0,
            "lote": "—",
            "validade": None,
            "dias_vencimento": None,
            "local": "Almoxarifado B",
            "status": "sem_estoque",
            "valor_unitario": 0.12,
            "ultimo_recebimento": "2026-02-15",
        },
        {
            "id": "CATMAT-000330",
            "nome": "Doxiciclina 100mg (cp)",
            "codigo": "CATMAT-000330",
            "categoria": "Antibiótico",
            "unidade": "cp",
            "estoque_atual": 820,
            "estoque_minimo": 200,
            "estoque_maximo": 2000,
            "consumo_medio_mensal": 160,
            "meses_cobertura": 5.1,
            "lote": "DOX2026-0011",
            "validade": "2026-08-15",
            "dias_vencimento": 33,
            "local": "Almoxarifado A — Prateleira 5",
            "status": "alerta",
            "valor_unitario": 0.65,
            "ultimo_recebimento": "2026-04-08",
        },
        {
            "id": "CATMAT-000415",
            "nome": "Ivermectina 6mg (cp)",
            "codigo": "CATMAT-000415",
            "categoria": "Antiparasitário",
            "unidade": "cp",
            "estoque_atual": 3200,
            "estoque_minimo": 400,
            "estoque_maximo": 5000,
            "consumo_medio_mensal": 380,
            "meses_cobertura": 8.4,
            "lote": "IVE2026-0005",
            "validade": "2028-02-28",
            "dias_vencimento": 942,
            "local": "Almoxarifado A — Prateleira 6",
            "status": "ok",
            "valor_unitario": 0.42,
            "ultimo_recebimento": "2026-06-15",
        },
    ]
    if categoria:
        itens = [i for i in itens if i["categoria"].lower() == categoria.lower()]
    return {
        "situacao_dado": "referencia_municipal",
        "total": len(itens),
        "itens": itens,
    }
