"""Frota de Saúde — Veículos · Manutenção · Disponibilidade · FMS Apuí/AM"""
from fastapi import APIRouter

router = APIRouter(prefix="/api/frota", tags=["frota"])


@router.get("/dashboard")
async def dashboard():
    return {
        "situacao_dado": "referencia_municipal",
        "municipio": "Apuí/AM",
        "competencia": "Mar/2026",
        "total_veiculos": 12,
        "disponiveis": 9,
        "manutencao": 2,
        "inoperantes": 1,
        "disponibilidade_pct": 75.0,
        "veiculos_vencidos_revisao": 3,
        "pacientes_transportados_mes": 312,
        "viagens_mes": 184,
        "custo_combustivel_mes": 18640,
    }


@router.get("/historico")
async def historico():
    return [
        {"situacao_dado": "referencia_municipal", "mes": "Out/25", "viagens": 164, "pacientes": 278, "disponibilidade_pct": 83.3},
        {"situacao_dado": "referencia_municipal", "mes": "Nov/25", "viagens": 172, "pacientes": 291, "disponibilidade_pct": 83.3},
        {"situacao_dado": "referencia_municipal", "mes": "Dez/25", "viagens": 148, "pacientes": 258, "disponibilidade_pct": 75.0},
        {"situacao_dado": "referencia_municipal", "mes": "Jan/26", "viagens": 176, "pacientes": 298, "disponibilidade_pct": 75.0},
        {"situacao_dado": "referencia_municipal", "mes": "Fev/26", "viagens": 180, "pacientes": 304, "disponibilidade_pct": 75.0},
        {"situacao_dado": "referencia_municipal", "mes": "Mar/26", "viagens": 184, "pacientes": 312, "disponibilidade_pct": 75.0},
    ]


@router.get("/veiculos")
async def veiculos():
    return [
        {
            "situacao_dado": "referencia_municipal",
            "placa": "QRX-4281",
            "tipo": "Ambulância USB (SAMU)",
            "ano": 2021,
            "lotacao": "SAMU 192 Apuí",
            "status": "disponivel",
            "km_atual": 84210,
            "proxima_revisao_km": 90000,
            "combustivel": "Diesel",
            "observacao": None,
        },
        {
            "situacao_dado": "referencia_municipal",
            "placa": "QRY-1842",
            "tipo": "Van de Transporte Sanitário",
            "ano": 2019,
            "lotacao": "TFD / Referência Humaitá",
            "status": "disponivel",
            "km_atual": 148930,
            "proxima_revisao_km": 150000,
            "combustivel": "Diesel",
            "observacao": "Revisão de 150.000 km próxima — agendar preventiva.",
        },
        {
            "situacao_dado": "referencia_municipal",
            "placa": "QRX-9014",
            "tipo": "Van de Transporte Sanitário",
            "ano": 2020,
            "lotacao": "TFD / Referência Manaus",
            "status": "disponivel",
            "km_atual": 112480,
            "proxima_revisao_km": 120000,
            "combustivel": "Diesel",
            "observacao": None,
        },
        {
            "situacao_dado": "referencia_municipal",
            "placa": "QSA-3328",
            "tipo": "Veículo Leve (Supervisor ACS)",
            "ano": 2018,
            "lotacao": "Coordenação APS",
            "status": "manutencao",
            "km_atual": 198740,
            "proxima_revisao_km": 200000,
            "combustivel": "Flex",
            "observacao": "Caixa de câmbio em reparo — previsão retorno 10 dias.",
        },
        {
            "situacao_dado": "referencia_municipal",
            "placa": "QSA-4401",
            "tipo": "Caminhonete 4x4 (Zona Rural)",
            "ano": 2017,
            "lotacao": "ESF Rio Juma / Zona Rural",
            "status": "disponivel",
            "km_atual": 224560,
            "proxima_revisao_km": 230000,
            "combustivel": "Diesel",
            "observacao": None,
        },
        {
            "situacao_dado": "referencia_municipal",
            "placa": "QRZ-8812",
            "tipo": "Micro-ônibus (Transporte Coletivo Saúde)",
            "ano": 2016,
            "lotacao": "Transporte pacientes TFD coletivo",
            "status": "disponivel",
            "km_atual": 312880,
            "proxima_revisao_km": 320000,
            "combustivel": "Diesel",
            "observacao": None,
        },
        {
            "situacao_dado": "referencia_municipal",
            "placa": "QSB-2267",
            "tipo": "Veículo Leve (Vigilância Sanitária)",
            "ano": 2020,
            "lotacao": "VISA Municipal",
            "status": "disponivel",
            "km_atual": 78420,
            "proxima_revisao_km": 90000,
            "combustivel": "Flex",
            "observacao": None,
        },
        {
            "situacao_dado": "referencia_municipal",
            "placa": "QSB-7741",
            "tipo": "Veículo Leve (Epidemiologia)",
            "ano": 2021,
            "lotacao": "Vigilância Epidemiológica",
            "status": "disponivel",
            "km_atual": 62110,
            "proxima_revisao_km": 80000,
            "combustivel": "Flex",
            "observacao": None,
        },
        {
            "situacao_dado": "referencia_municipal",
            "placa": "QSC-1102",
            "tipo": "Caminhonete 4x4 (ACS Ribeirinho)",
            "ano": 2018,
            "lotacao": "ACS Comunidades Rio Madeira",
            "status": "manutencao",
            "km_atual": 187240,
            "proxima_revisao_km": 190000,
            "combustivel": "Diesel",
            "observacao": "Sistema de freios em revisão — retorno previsto em 7 dias.",
        },
        {
            "situacao_dado": "referencia_municipal",
            "placa": "QRW-5598",
            "tipo": "Veículo Leve (Gestão SMS)",
            "ano": 2022,
            "lotacao": "Secretaria Municipal de Saúde",
            "status": "disponivel",
            "km_atual": 38940,
            "proxima_revisao_km": 60000,
            "combustivel": "Flex",
            "observacao": None,
        },
        {
            "situacao_dado": "referencia_municipal",
            "placa": "AM-0047",
            "tipo": "Lancha Fluvial (Rio Madeira)",
            "ano": 2019,
            "lotacao": "SAMU / ACS Ribeirinho",
            "status": "inoperante",
            "km_atual": None,
            "proxima_revisao_km": None,
            "combustivel": "Gasolina",
            "observacao": "Motor avariado desde 12/02/2026. Orçamento reparo: R$ 28.400 — empenho pendente.",
        },
        {
            "situacao_dado": "referencia_municipal",
            "placa": "QRC-8830",
            "tipo": "Veículo Leve (Farmácia Básica)",
            "ano": 2019,
            "lotacao": "Assistência Farmacêutica",
            "status": "disponivel",
            "km_atual": 104580,
            "proxima_revisao_km": 110000,
            "combustivel": "Flex",
            "observacao": None,
        },
    ]


@router.get("/manutencoes")
async def manutencoes():
    return [
        {
            "situacao_dado": "referencia_municipal",
            "veiculo": "QSA-3328 — Veículo Leve",
            "tipo_manutencao": "Corretiva — Câmbio",
            "oficina": "Auto Mecânica Apuí Ltda",
            "data_entrada": "2026-03-08",
            "previsao_saida": "2026-03-18",
            "custo_estimado": 4800,
            "status": "em_andamento",
        },
        {
            "situacao_dado": "referencia_municipal",
            "veiculo": "QSC-1102 — Caminhonete 4x4",
            "tipo_manutencao": "Corretiva — Sistema de freios",
            "oficina": "Auto Mecânica Apuí Ltda",
            "data_entrada": "2026-03-11",
            "previsao_saida": "2026-03-18",
            "custo_estimado": 2200,
            "status": "em_andamento",
        },
        {
            "situacao_dado": "referencia_municipal",
            "veiculo": "QRY-1842 — Van TFD",
            "tipo_manutencao": "Preventiva — 150.000 km",
            "oficina": "Concessionária Humaitá (a confirmar)",
            "data_entrada": None,
            "previsao_saida": None,
            "custo_estimado": 3600,
            "status": "agendada",
        },
        {
            "situacao_dado": "referencia_municipal",
            "veiculo": "AM-0047 — Lancha Fluvial",
            "tipo_manutencao": "Corretiva — Motor náutico",
            "oficina": "Aguardando licitação",
            "data_entrada": "2026-02-12",
            "previsao_saida": None,
            "custo_estimado": 28400,
            "status": "pendente",
        },
    ]
